# -*- coding: utf-8 -*-
"""Lagrange-Lock PPO Training (Colab Version)

Automatically generated by Antigravity.
Optimized for Google Colab Free Tier (T4 GPU).
"""

import os
import sys
import numpy as np
import gymnasium as gym
from gymnasium import spaces
import torch
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import SubprocVecEnv, DummyVecEnv
from stable_baselines3.common.callbacks import CheckpointCallback, EvalCallback
from stable_baselines3.common.env_util import make_vec_env
from stable_baselines3.common.monitor import Monitor

# --- 1. JIT DYNAMICS (INLINED) ---
# We inline this to make the script self-contained for Colab.
try:
    from numba import njit
except ImportError:
    print("Installing Numba...")
    # On Colab, usually pre-installed, but just in case
    import subprocess
    subprocess.check_call([sys.executable, "-m", "pip", "install", "numba"])
    from numba import njit

print("Compiling JIT Dynamics...")

@njit(cache=False)
def cr3bp_derivs(state, mu):
    x, y, z, vx, vy, vz = state
    # Primary (Earth): (-mu, 0, 0)
    r1 = np.sqrt((x + mu)**2 + y**2 + z**2)
    # Secondary (Moon): (1-mu, 0, 0)
    r2 = np.sqrt((x - (1 - mu))**2 + y**2 + z**2)
    
    # CR3BP Equations
    ax = 2 * vy + x - ((1 - mu) * (x + mu) / r1**3) - (mu * (x - (1 - mu)) / r2**3)
    ay = -2 * vx + y - ((1 - mu) * y / r1**3) - (mu * y / r2**3)
    az = -((1 - mu) * z / r1**3) - (mu * z / r2**3)
    
    return np.array([vx, vy, vz, ax, ay, az], dtype=np.float64)

@njit(cache=False)
def rk4_step(state, dt, mu):
    k1 = cr3bp_derivs(state, mu)
    k2 = cr3bp_derivs(state + 0.5 * dt * k1, mu)
    k3 = cr3bp_derivs(state + 0.5 * dt * k2, mu)
    k4 = cr3bp_derivs(state + dt * k3, mu)
    return state + (dt / 6.0) * (k1 + 2*k2 + 2*k3 + k4)

print("Dynamics Compiled.")

# --- 2. ENVIRONMENT ---

class SatelliteEnv(gym.Env):
    def __init__(self, mu=0.01215):
        super(SatelliteEnv, self).__init__()
        self.mu = mu
        self.dt = 0.01
        
        # Target: L1 Approx
        self.target_pos = np.array([0.836915, 0, 0], dtype=np.float64)
        
        # Action: Thrust (Fx, Fy, Fz) - Continuous
        self.action_space = spaces.Box(low=-1.0, high=1.0, shape=(3,), dtype=np.float32)
        
        # Obs: [x, y, z, vx, vy, vz, fuel]
        self.observation_space = spaces.Box(low=-10.0, high=10.0, shape=(7,), dtype=np.float32)
        
        self.state = np.zeros(6)
        self.fuel = 1.0
        self.max_steps = 4000 # Extended for longer orbit maintenance
        self.current_step = 0
        self.max_thrust = 0.5
        self.fuel_consumption = 0.0005

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        # Init near L1 with random noise
        noise = self.np_random.uniform(low=-0.02, high=0.02, size=(6,))
        self.state = np.concatenate([self.target_pos, [0, 0, 0]]) + noise
        self.fuel = 1.0
        self.current_step = 0
        return self._get_obs(), {}

    def step(self, action):
        self.current_step += 1
        action = np.clip(action, -1.0, 1.0)
        
        # Fuel Logic
        thrust_mag = np.linalg.norm(action)
        if self.fuel <= 0:
            action[:] = 0
            thrust_mag = 0
        else:
            self.fuel -= thrust_mag * self.fuel_consumption
            if self.fuel < 0: self.fuel = 0.0
            
        # Physics (Impulse Control matches Viewer)
        thrust_vec = action * self.max_thrust
        
        # 1. Natural Gravity Check (RK4)
        self.state = rk4_step(self.state, self.dt, self.mu)
        
        # 2. Thrust Impulse
        self.state[3:6] += thrust_vec * self.dt
        
        # Reward
        pos = self.state[:3]
        dist = np.linalg.norm(pos - self.target_pos)
        vel_mag = np.linalg.norm(self.state[3:6])
        
        reward = 0.1 # Survival
        
        if dist < 0.05:
            reward += 1.0 # Tight Halo bonus
        elif dist < 0.15:
            reward += 0.5 # Loose Halo bonus
            
        # Penalties
        reward -= 0.1 * vel_mag # Stabilize velocity
        reward -= 0.2 * (thrust_mag**2) # Save Fuel
        if dist > 0.1:
            reward -= 2.0 * (dist - 0.1) # Soft tether
            
        terminated = False
        truncated = False
        
        if dist > 0.3: # Crash/Lost
            terminated = True
            reward -= 100.0
            
        if self.current_step >= self.max_steps:
            truncated = True
            
        return self._get_obs(), reward, terminated, truncated, {}

    def _get_obs(self):
        obs = np.empty(7, dtype=np.float32)
        obs[:6] = self.state.astype(np.float32)
        obs[6] = float(self.fuel)
        return obs

# --- 3. TRAINING SETUP ---

def train():
    # Install dependencies if missing (Colab specific)
    try:
        import stable_baselines3
    except ImportError:
        subprocess.check_call([sys.executable, "-m", "pip", "install", "stable-baselines3[extra]"])
    
    # Environment Setup
    # Use SubprocVecEnv for CPU parallelism. Colab usually gives 2 cores.
    num_cpu = 8 # Try 8, Colab might throttle, but 4 is safe.
    env = make_vec_env(SatelliteEnv, n_envs=num_cpu, vec_env_cls=SubprocVecEnv)
    
    # PPO Hyperparameters (Optimized for Continuous Control)
    model = PPO(
        "MlpPolicy",
        env,
        verbose=1,
        learning_rate=3e-4,
        n_steps=2048,
        batch_size=1024, # Large batch for stable gradient
        n_epochs=10,
        gamma=0.99,
        gae_lambda=0.95,
        clip_range=0.2,
        ent_coef=0.005, # Slight exploration
        policy_kwargs=dict(net_arch=[dict(pi=[256, 256], vf=[256, 256])]),
        device='cuda' # FORCE GPU
    )
    
    # Callbacks
    checkpoint_callback = CheckpointCallback(
        save_freq=1000000 // num_cpu,
        save_path='./logs/',
        name_prefix='ppo_satellite'
    )
    
    print("Refueling... Launching Training on GPU...")
    print("Target: 80 Million Steps (approx 10 hours @ 2M/15min)")
    
    # 80 Million steps
    model.learn(total_timesteps=80_000_000, callback=checkpoint_callback, progress_bar=True)
    
    model.save("final_model_ppo")
    print("Training Complete. Model saved as 'final_model_ppo.zip'")
    
    # Export to ONNX
    export_onnx(model)

def export_onnx(model):
    print("Exporting to ONNX...")
    import torch
    import torch.nn as nn
    
    class OnnxPolicy(nn.Module):
        def __init__(self, extractor, action_net):
            super().__init__()
            self.extractor = extractor
            self.action_net = action_net
        def forward(self, obs):
            features = self.extractor(obs)
            return self.action_net(features)

    onnx_policy = OnnxPolicy(model.policy.mlp_extractor.policy_net, model.policy.action_net)
    onnx_policy.eval()
    
    dummy_input = torch.randn(1, 7, device='cuda')
    torch.onnx.export(
        onnx_policy,
        dummy_input,
        "model.onnx",
        opset_version=11,
        input_names=["input"],
        output_names=["output"]
    )
    print("Exported to model.onnx")

if __name__ == "__main__":
    train()
